services:
  - type: web
    name: yt-audio-server
    env: node
    runtime: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
